### ISSUE TITLE
bug(dataflow): 23 pre-existing SQLite test failures on main (pytest -k sqlite)

### ISSUE THREAD

**Issue by esperie** [terrene-foundation/kailash-py#1498]
## Summary

`pytest -k sqlite` over `packages/kailash-dataflow/tests` reports **~25 failures on `main`** (present in released 2.45.1 / kailash-dataflow 2.13.2 — not introduced by any recent change). They span **≥4 distinct root causes**, i.e. this is heterogeneous test-vs-API drift, not a single bug.

## Sampled root-cause clusters (evidence)

1. **`AttributeError: 'LocalRuntime' object has no attribute 'execute_workflow_async'`** — e.g. `tests/integration/model_registry/test_model_registry_integration.py::...::test_register_model_real_database[sqlite_memory]`. `model_registry.py:_run_in_thread` calls `execute_workflow_async` on a `LocalRuntime` (that method is on `AsyncLocalRuntime`).
2. **`KeyError: 'price'`** on upsert result shape — `tests/integration/test_single_upsert_node.py::TestSQLiteUpsertNode::test_sqlite_upsert_full_cycle` (with a preceding `ERROR:dataflow.core.model_registry: ... Failed to register pending model: Product`).
3. **`RuntimeError: create_tables() cannot be called from a running async context ... (DF-501)`** — `tests/e2e/applications/test_dataflow_basic_e2e.py::test_basic_dataflow_operations[sqlite_memory]`; the test calls sync `create_tables()` inside an async context.
4. **Stale assertion** — `tests/integration/adapters/test_sqlite_adapter_integration.py::...::test_adapter_initialization_memory` asserts `adapter.database_path == ":memory:"`, but the adapter rewrites `:memory:` to a shared-cache URI (`file:dataflow_<n>?mode=memory&cache=shared`).

Other failing files in the set include `test_single_upsert_conflict_fields.py`, `test_sqlite_integration.py` (`test_auto_generated_nodes`, `test_schema_migration`), `test_sync_ddl_auto_migrate.py`, and `test_dataflow_health_check_workflow_fix.py`.

## Acceptance criteria
- [ ] Triage each failing `-k sqlite` test into: real product bug vs stale-test-vs-API drift.
- [ ] Fix product bugs (e.g. the `LocalRuntime`/`AsyncLocalRuntime` mismatch, the upsert result-shape / model-registration failures) and update stale tests to the current adapter/runtime contract.
- [ ] `pytest -k sqlite` over `packages/kailash-dataflow/tests` is green (or remaining skips are justified per test-skip-discipline).

## Notes
Surfaced during the F-AIOSQLITE fix (kailash-dataflow 2.13.3). Reproduce with `.venv/bin/python -m pytest packages/kailash-dataflow/tests -k sqlite -q` (use `.venv/bin/python`, not `uv run` — pre-existing conftest loom-path import issue in editable installs). Likely a multi-shard effort.

**Comment by esperie** [comment]
## Triage progress (session 2026-07-03)

**Cluster 1 — FIXED in #1500** (7 of the original 23 `-k sqlite` failures): `ModelRegistry._execute_workflow_sync_safe` re-read the parent DataFlow's per-event-loop runtime property inside the worker-thread offload branch, where the loop-less context re-resolved it to the sync `LocalRuntime` singleton → `AttributeError: 'LocalRuntime' object has no attribute 'execute_workflow_async'`. Resolve-once fix. (Also fixed a latent `NameError` in the uncalled `get_model_version`.)

`-k sqlite`: **23 → 16 failures** after #1500.

### Remaining 16 — triaged (product-bug vs stale-test)

**PRODUCT BUG — upsert returns a DML summary, not the upserted row (4)**
- `test_single_upsert_node.py::{test_sqlite_upsert_full_cycle, test_sqlite_string_id_preservation}`
- `test_single_upsert_conflict_fields.py::{test_sqlite_upsert_sku_conflict, test_sqlite_upsert_composite_conflict}`
- Evidence: `ProductUpsertNode` returns `{"created": true, "record": {"rows_affected": 0}, "action": "created"}` — `record` is a DML row-count summary, not the row. Tests assert `record["price"]` / `record["id"]`. The node needs to return the upserted row (e.g. `RETURNING`) for SQLite. `created: true` alongside `rows_affected: 0` is also suspect.

**PRODUCT BUG — auto-migrate silently fails under a running event loop (2)**
- `test_sync_ddl_auto_migrate.py::{test_auto_migrate_sqlite_no_event_loop, test_auto_migrate_sqlite_with_running_event_loop}`
- Evidence: `result["success"]` is `False` with `result["error"]` `None` (DF-501 path) — silent failure.

**STALE TEST — asserts the pre-rewrite `:memory:` path (1)**
- `test_sqlite_adapter_integration.py::test_adapter_initialization_memory` asserts `adapter.database_path == ":memory:"`, but the adapter intentionally rewrites `:memory:` → `file:dataflow_<id>?mode=memory&cache=shared` (shared-cache, so pooled connections see one DB). The very next line `assert adapter.is_memory_database is True` already validates the real contract. Fix: update the stale assertion.

**NOT YET ROOT-CAUSED (9)** — need per-test dig:
- `test_register_model_real_database[sqlite_memory]` → `no such table: dataflow_model_registry` (registry table not created for `:memory:` — likely product).
- `test_dataflow_basic_e2e.py::test_basic_dataflow_operations[sqlite_file, sqlite_memory]` (2)
- `test_production_dataflow.py::test_sqlite_crud_operations`
- `test_sqlite_integration.py::{test_auto_generated_nodes, test_schema_migration}` (2)
- `test_dataflow_health_check_workflow_fix.py::test_dataflow_sqlite_workflow_complete`
- `test_sqlite_adapter_integration.py::{test_get_database_size, test_wal_mode_enabled}` (2)

These remaining clusters are independent root causes (per the issue's "multi-shard effort" note) and are best taken as follow-up shards. All 16 confirmed pre-existing on `main` (unchanged by #1499/#1500).
